export default [
  '',
  'em em-angry',
  'em em-8ball',
  'em em-apple',
  'em em-baby',
  'em em-kiss',
  'em em-lock',
  'em em-battery',
  'em em-iphone',
  'em em-basketball',
  'em em-mailbox',
  'em em-horse',
  'em em-bowling',
  'em em-ear',
  'em em-cop',
  'em em-frog',
  'em em-dart',
];
